"""
ChromaDB Store Manager
Handles vector storage with metadata for Neo4j linking.
"""

import chromadb
from chromadb.config import Settings
from typing import List, Dict, Any, Optional
import uuid
from pathlib import Path


class ChromaStore:
    """
    Manages ChromaDB vector store with persistent storage.
    
    Features:
    - Persistent storage (survives restarts)
    - Metadata filtering (law, chapter, section)
    - Neo4j linking via node IDs
    - Cosine similarity search
    """
    
    def __init__(
        self, 
        persist_directory: str = "./chroma_db",
        collection_name: str = "legal_docs"
    ):
        """
        Initialize ChromaDB client.
        
        Args:
            persist_directory: Path to store database
            collection_name: Name of the collection
        """
        self.persist_directory = Path(persist_directory)
        self.persist_directory.mkdir(parents=True, exist_ok=True)
        
        print(f"Initializing ChromaDB at: {self.persist_directory}")
        
        # Create persistent client
        self.client = chromadb.PersistentClient(
            path=str(self.persist_directory)
        )
        
        # Get or create collection
        self.collection = self.client.get_or_create_collection(
            name=collection_name,
            metadata={"hnsw:space": "cosine"}  # Cosine similarity
        )
        print(f"[OK] Collection handled: {collection_name}")
        print(f"  Current document count: {self.collection.count()}")
    
    def add_chunks(
        self, 
        chunks: List[Dict[str, Any]],
        embeddings: List[List[float]],
        generate_neo4j_ids: bool = True
    ) -> List[str]:
        """
        Add chunks to ChromaDB with embeddings and metadata.
        
        Args:
            chunks: List of chunk dicts with 'text' and 'metadata'
            embeddings: List of embedding vectors (384-dim)
            generate_neo4j_ids: Generate UUIDs for Neo4j linking
            
        Returns:
            List of generated IDs
        """
        if len(chunks) != len(embeddings):
            raise ValueError(f"Chunks ({len(chunks)}) and embeddings ({len(embeddings)}) count mismatch")
        
        documents = []
        metadatas = []
        ids = []
        
        for i, chunk in enumerate(chunks):
            # Use deterministic chunk_id from metadata (generated by semantic_chunker)
            chunk_id = chunk['metadata'].get('chunk_id')
            
            if not chunk_id:
                # Fallback: generate ID if not present (shouldn't happen with updated chunker)
                chunk_id = f"{chunk['metadata']['law_title']}_{chunk['metadata']['section']}_{chunk['metadata']['chunk_index']}"
                chunk_id = chunk_id.replace(" ", "_").replace("/", "_")
                print(f"[!] Warning: chunk_id not found in metadata, using fallback ID")
            
            # Neo4j linking (optional, for backward compatibility)
            if generate_neo4j_ids and 'neo4j_chunk_id' not in chunk['metadata']:
                # Use chunk_id as neo4j_chunk_id if not already set
                chunk['metadata']['neo4j_chunk_id'] = chunk_id
            
            # Prepare metadata for ChromaDB (filter None values, convert lists to JSON)
            import json
            metadata_for_chroma = {}
            for key, value in chunk['metadata'].items():
                if value is not None:  # Skip None values
                    if isinstance(value, list):
                        metadata_for_chroma[key] = json.dumps(value)
                    elif isinstance(value, dict):
                        metadata_for_chroma[key] = json.dumps(value)
                    else:
                        metadata_for_chroma[key] = value
            
            documents.append(chunk['text'])
            metadatas.append(metadata_for_chroma)
            ids.append(chunk_id)
        
        # Add to ChromaDB
        self.collection.add(
            documents=documents,
            embeddings=embeddings,
            metadatas=metadatas,
            ids=ids
        )
        
        print(f"[OK] Added {len(chunks)} chunks to ChromaDB")
        return ids
    
    def query(
        self,
        query_embedding: List[float],
        n_results: int = 5,
        where: Optional[Dict[str, Any]] = None
    ) -> Dict[str, Any]:
        """
        Query ChromaDB for similar chunks.
        
        Args:
            query_embedding: Query vector (384-dim)
            n_results: Number of results to return
            where: Metadata filter (e.g., {"law": "Forest Act 1927"})
            
        Returns:
            Query results with documents, metadatas, distances
        """
        results = self.collection.query(
            query_embeddings=[query_embedding],
            n_results=n_results,
            where=where
        )
        
        return results
    
    def query_by_text(
        self,
        query_text: str,
        embedding_generator,
        n_results: int = 5,
        where: Optional[Dict[str, Any]] = None
    ) -> Dict[str, Any]:
        """
        Query using text (generates embedding internally).
        
        Args:
            query_text: Query string
            embedding_generator: EmbeddingGenerator instance
            n_results: Number of results
            where: Metadata filter
            
        Returns:
            Query results
        """
        query_embedding = embedding_generator.encode_single(query_text)
        return self.query(query_embedding.tolist(), n_results, where)
    
    def get_collection_stats(self) -> Dict[str, Any]:
        """Get collection statistics."""
        count = self.collection.count()
        
        # Get sample to analyze metadata
        sample = self.collection.peek(limit=10)
        
        return {
            "total_documents": count,
            "collection_name": self.collection.name,
            "persist_directory": str(self.persist_directory),
            "sample_metadata": sample['metadatas'][:3] if sample['metadatas'] else []
        }
    
    def delete_collection(self):
        """Delete the collection (use with caution!)."""
        self.client.delete_collection(name=self.collection.name)
        print(f"[OK] Deleted collection: {self.collection.name}")


if __name__ == "__main__":
    # Test
    from embedding_generator import EmbeddingGenerator
    
    # Initialize
    store = ChromaStore(persist_directory="./test_chroma_db")
    generator = EmbeddingGenerator()
    
    # Create test chunks
    test_chunks = [
        {
            'text': "Section 1: This Act may be called the Forest Act, 1927",
            'metadata': {
                'law': 'Forest Act 1927',
                'chapter': 'Chapter I',
                'section': '1',
                'section_title': 'Short title',
                'chunk_index': 0,
                'total_chunks': 1
            }
        },
        {
            'text': "Section 2: In this Act, forest means a reserved forest",
            'metadata': {
                'law': 'Forest Act 1927',
                'chapter': 'Chapter I',
                'section': '2',
                'section_title': 'Definitions',
                'chunk_index': 0,
                'total_chunks': 1
            }
        }
    ]
    
    # Generate embeddings
    texts = [chunk['text'] for chunk in test_chunks]
    embeddings = generator.encode(texts, show_progress=False)
    
    # Add to ChromaDB
    ids = store.add_chunks(test_chunks, embeddings.tolist())
    print(f"\nAdded IDs: {ids}")
    
    # Query
    results = store.query_by_text(
        "What is the definition of forest?",
        generator,
        n_results=2
    )
    
    print(f"\nQuery results:")
    for i, (doc, meta, dist) in enumerate(zip(
        results['documents'][0],
        results['metadatas'][0],
        results['distances'][0]
    )):
        print(f"\n{i+1}. Distance: {dist:.4f}")
        print(f"   Section: {meta['section']}")
        print(f"   Text: {doc[:100]}...")
    
    # Stats
    stats = store.get_collection_stats()
    print(f"\nCollection stats: {stats}")
