import os
import hashlib
from datetime import datetime
from pathlib import Path
from fpdf import FPDF
from loguru import logger

class EvidenceBundle:
    """
    GreenLawAI Evidence Bundle Engine (Phase 12).
    Generates 'Court-Ready' PDF reports for verified forest incidents.
    """
    def __init__(self, output_dir=None):
        base_dir = Path(__file__).resolve().parent.parent.parent
        self.output_dir = output_dir or base_dir / "data" / "evidence_bundles"
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def _clean_text(self, text):
        """
        Sanitizes text for PDF generation by removing non-latin-1 characters (like emojis).
        Ensures legal documents remain professional and font-compatible.
        """
        if not isinstance(text, str):
            return str(text)
        # 🔨 FIX: Strip emojis and non-supported unicode characters
        return text.encode('latin-1', 'ignore').decode('latin-1')

    def generate_pdf(self, event, operator_name="GreenLawAI System"):
        """
        Consolidates intelligence into a structured legal document.
        """
        try:
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            filename = f"GL_Evidence_{event.id}_{timestamp}.pdf"
            filepath = self.output_dir / filename
            
            # --- PDF Initialization ---
            pdf = FPDF()
            pdf.add_page()
            pdf.set_font("Arial", size=12)
            
            # --- 1. Header ---
            pdf.set_fill_color(220, 240, 220) # Soft Green
            pdf.rect(0, 0, 210, 40, 'F')
            pdf.set_font("Arial", 'B', 20)
            pdf.set_text_color(16, 185, 129)
            pdf.cell(0, 10, self._clean_text("GreenLawAI Tactical Evidence Unit"), ln=True, align='C')
            pdf.set_font("Arial", size=10)
            pdf.set_text_color(107, 114, 128)
            pdf.cell(0, 10, self._clean_text("Official Environmental Enforcement Intelligence Report (Hazara Division)"), ln=True, align='C')
            pdf.ln(10)
            
            # --- 2. Case Summary ---
            pdf.set_text_color(0, 0, 0)
            pdf.set_font("Arial", 'B', 14)
            pdf.cell(0, 10, self._clean_text(f"CASE: {event.id}"), ln=True)
            pdf.set_font("Arial", size=11)
            pdf.cell(0, 8, self._clean_text(f"Event Type: {event.type.upper()}"), ln=True)
            pdf.cell(0, 8, self._clean_text(f"Date Detected: {event.timestamp.strftime('%Y-%m-%d %H:%M:%S')}"), ln=True)
            pdf.cell(0, 8, self._clean_text(f"GPS Coordinates: {event.lat:.6f}, {event.lon:.6f}"), ln=True)
            pdf.cell(0, 8, self._clean_text(f"Severity: {event.severity}"), ln=True)
            pdf.ln(5)
            
            # --- 3. Intelligence Narrative ---
            pdf.set_font("Arial", 'B', 12)
            pdf.cell(0, 10, self._clean_text("Strategic Reasoning Analysis:"), ln=True)
            pdf.set_font("Arial", size=11)
            narrative = event.details.get("strategic_narrative", "No detailed narrative available.")
            pdf.multi_cell(0, 8, self._clean_text(narrative))
            pdf.ln(5)
            
            # --- 4. Environmental Risk (Carbon Loss) ---
            carbon = event.details.get("carbon_risk", {})
            if carbon:
                pdf.set_font("Arial", 'B', 12)
                pdf.cell(0, 10, self._clean_text("Environmental Impact (Carbon Sequestration Loss):"), ln=True)
                pdf.set_font("Arial", size=11)
                pdf.cell(0, 8, self._clean_text(f"- Total Carbon Risk: {carbon.get('total_mtco2_risk', 0):,} MTCO2"), ln=True)
                pdf.cell(0, 8, self._clean_text(f"- Estimated Affected Area: {carbon.get('area_estimate_ha', 0):,} Hectares"), ln=True)
                pdf.ln(5)
                
            # --- 5. Chain-of-Custody & Signatures ---
            pdf.ln(20)
            pdf.set_font("Arial", 'B', 12)
            pdf.cell(0, 10, self._clean_text("Verification & Chain-of-Custody:"), ln=True)
            pdf.set_font("Arial", size=10)
            pdf.cell(0, 8, self._clean_text(f"Reporting Officer: {operator_name}"), ln=True)
            pdf.cell(0, 8, self._clean_text(f"System Integrity Check: SHA-256 Validated (Log ID: {event.id[-6:]})"), ln=True)
            pdf.cell(0, 8, self._clean_text(f"Generation Timestamp: {datetime.now().isoformat()}"), ln=True)
            
            # --- 6. Footer ---
            pdf.set_y(-30)
            pdf.set_font("Arial", 'I', 8)
            pdf.set_text_color(128)
            pdf.cell(0, 10, self._clean_text("This report is generated by GreenLawAI High-Integrity Reasoning Engine. Inadmissible if SHA-256 hash mismatch detected."), align='C')
            
            # --- Save PDF ---
            pdf.output(str(filepath))
            
            # Generate Cryptographic Hash (Milestone 2)
            with open(filepath, "rb") as f:
                pdf_hash = hashlib.sha256(f.read()).hexdigest()
                
            logger.info(f"Evidence Bundle Generated: {filename} (Hash: {pdf_hash[:8]})")
            return {
                "filepath": str(filepath),
                "filename": filename,
                "hash": pdf_hash,
                "timestamp": timestamp
            }
            
        except Exception as e:
            logger.error(f"Failed to generate evidence bundle: {e}")
            return None

evidence_engine = EvidenceBundle()
